### PR TITLE
Add common Unity awaits to `PromiseYielder`

### LINKED ISSUE #196: Promises wrapper for Unity's AssetBundle.LoadAssetAsync()?
Hi,

What is the proper `Promises` invocation to wrap Unity's `AssetBundle.LoadAssetAsync()`?

When using `UnityAsync`, I was just able to call:
 ```.cs
T obj = await _assetBundle.LoadAssetAsync<T>(nameID);
```

But using `Promises` I'm unclear if there's even a convenience wrapper or what it looks like under Promises in this case.

### LINKED ISSUE #199: `PromiseYielder.WaitOneFrame()` waits an extra frame.
This test fails. It appears to be due to the optimization I added that continues to use the already-running coroutine rather than starting a new coroutine. I'm not sure why it happens, but the first call waits 1 frame, and successive (recursive) calls wait 2 frames.

```cs
[UnityTest]
public IEnumerator PromiseYielderWaitOneFrame_WaitsOneFrameMultiple(
    [Values] RunnerType runnerType)
{
    int currentFrame = Time.frameCount;

    var promise = PromiseYielder.WaitOneFrame(GetRunner(runnerType))
        .Then(() =>
        {
            Assert.AreEqual(currentFrame + 1, Time.frameCount);
            return PromiseYielder.WaitOneFrame(GetRunner(runnerType));
        })
        .Then(() =>
        {
            Assert.AreEqual(currentFrame + 2, Time.frameCount);
            return PromiseYielder.WaitOneFrame(GetRunner(runnerType));
        })
        .Then(() =>
        {
            Assert.AreEqual(currentFrame + 3, Time.frameCount);
            return PromiseYielder.WaitOneFrame(GetRunner(runnerType));
        })
        .Then(() =>
        {
            Assert.AreEqual(currentFrame + 4, Time.frameCount);
        });
    using (var yieldInstruction = promise.ToYieldInstruction())
    {
        yield return yieldInstruction;
        if (yieldInstruction.State == Promise.State.Rejected)
            yieldInstruction.GetResult();
    }
}
```

Unfortunately, it seems the only way to fix it is to remove the optimization and always start a new coroutine. At least I am working on more optimized Unity awaits (#196) to offset the performance regression.

### PR DESCRIPTION
**Pull request by timcassell**
Fixes #199 and resolves #196.

Optimized `PromiseYielder.WaitOneFrame()`. (now 4x faster than `yield return null`)
Deprecated `PromiseYielder.WaitOneFrame(MonoBehaviour)`. (Breaking change, `WaitOneFrame()` returns a different type now)
Added common Unity awaits to `PromiseYielder`.

### CODE REVIEW

**Comment by timcassell** [comment]
@drew-512 Please take a look. I modeled this after `UnityAsync`.

You can wait on an `AsyncOperation` like this (cancelationToken is optional):

```cs
PromiseYielder.WaitForAsyncOperation(asyncOp).ToPromise(cancelationToken);
```
or
```cs
await PromiseYielder.WaitForAsyncOperation(asyncOp);
```
or
```cs
await PromiseYielder.WaitForAsyncOperation(asyncOp).WithCancelation(cancelationToken);
```
or
```cs
await PromiseYielder.WaitForAsyncOperation(asyncOp).AwaitWithProgress(0f, 1f, cancelationToken);
```

**Comment by drew-512** [comment]
Love it!  Plugging in the latest `main` today and will be testing it via my Unity AssetBundle wrappers and will report back.

**Comment by drew-512** [comment]
Looks like I should use the `promiseyielder-updates` branch!

**Comment by drew-512** [comment]
Looking good so far!

Will put in that latest commit this eve.

**Comment by timcassell** [comment]
@drew-512 Great! The only change I made in the last push was using Unity's time in `WaitForTime` instead of just scaling a system timer.

**Comment by drew-512** [comment]
LGTM

**Comment by timcassell** [comment]
@drew-512 Tyvm for your feedback!

**Pull request merged**
