### PR TITLE
Add `Promise.Manager.ResetRuntimeContext()` API

### LINKED ISSUE #283: Methods to troubleshoot UnobservedPromiseException
Hi Tim and friends,

I'm getting a `UnobservedPromiseException` show up a minute or two after I've stopped Unity when GC catches up.  This means I have zero info on where or why my code is not resolving a deferred promise.

Is there any way to have `PROMISE_DEBUG` record the top of stack trace when a deferred promise is created?  Another idea would be to allow a debug label (string) to be attached to a  promise.  In non-debug mode, the string is just dropped and not part of a promise struct, but in debug mode it would travel around with the promise allowing the developer to see its origin.

Drew

### PR DESCRIPTION
**Pull request by timcassell**
Fixes #283

### CODE REVIEW

**Comment by timcassell** [comment]
@drew-512 Want to give this a try?

**Comment by drew-512** [comment]
Hi Tim!

Been going about 6-7 hours of dev time with this branch (about 2-4 runs per hour, arena reload features all disabled).  The good news is I don't get the Promise not handled exception as raised previously.

However, 1 in 5 runs I get a Unity crash where the Unity crash reporter comes up etc.  I enabled `PROTO_PROMISE_DEVELOPER_MODE` and `PROTO_PROMISE_DEBUG_ENABLE` and no messages or change.

Happy to help support further, just lmk.

**Comment by timcassell** [comment]
Are you able to share the crash log?

**Comment by drew-512** [comment]
[14-Nov.zip](https://github.com/timcassell/ProtoPromise/files/13358217/14-Nov.zip)

Sure.  As I mentioned though, not seeing anything in it.  Best guess is the crash is happening before anything is written.  

Again, not sure yet.  This project is a AV player so there's a lot of stuff happening and I don't want to implicate PP just yet.  These crashes happen as the Unity debugger does suck.

**Comment by timcassell** [comment]
<details><summary>Log</summary>
<p>

``` cmd
Application is shutting down...
Cleanup mono
[40m[32minfo[39m[22m[49m: Unity.ILPP.Runner.PostProcessingAssemblyLoadContext[0]
      ALC ILPP context 1 is unloading
System Nova.Internal.DataStoreSystem Dispose failed with UnityEngine.UnityException: DestroyTransformAccessArray is not allowed to be called while application is terminating.
  at (wrapper managed-to-native) UnityEngine.Jobs.TransformAccessArray.DestroyTransformAccessArray(intptr)
  at UnityEngine.Jobs.TransformAccessArray.Dispose () [0x0001a] in /Users/bokken/build/output/unity/unity/Runtime/Transform/ScriptBindings/TransformAccessArray.bindings.cs:289 
  at Nova.Internal.Core.TransformDataStore`2[TDataStore,T].Dispose () [0x0002c] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Core/TransformDataStore.cs:221 
  at Nova.Internal.Layouts.LayoutDataStore.Dispose () [0x00001] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Layouts/LayoutDataStore.cs:758 
  at Nova.Internal.DataStoreSystem.Dispose () [0x00006] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/DataStoreSystem.cs:20 
  at Nova.Internal.Core.System`1[T].DomainReloadStarted () [0x00002] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Core/System.cs:50 
 #0 GetStacktrace(int)
 #1 DebugStringToFile(DebugStringToFileData const&)
 #2 DebugLogHandler_CUSTOM_Internal_Log(LogType, LogOption, ScriptingBackendNativeStringPtrOpaque*, ScriptingBackendNativeObjectPtrOpaque*)
 #3  (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)

System Nova.Internal.EngineManager Dispose failed with UnityEngine.UnityException: DestroyBuffer is not allowed to be called while application is terminating.
  at (wrapper managed-to-native) UnityEngine.ComputeBuffer.DestroyBuffer(UnityEngine.ComputeBuffer)
  at UnityEngine.ComputeBuffer.Dispose (System.Boolean disposing) [0x00007] in /Users/bokken/build/output/unity/unity/Runtime/Export/Shaders/ComputeBuffer.bindings.cs:44 
  at UnityEngine.ComputeBuffer.Dispose () [0x00001] in /Users/bokken/build/output/unity/unity/Runtime/Export/Shaders/ComputeBuffer.bindings.cs:35 
  at Nova.Internal.Rendering.ShaderBuffer.Dispose () [0x0000f] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Rendering/ShaderBuffer.cs:205 
  at Nova.Internal.Rendering.ShaderBufferUtils.SafeDispose (Nova.Internal.Rendering.ShaderBuffer shaderBuffer) [0x0000a] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Rendering/ShaderBuffer.cs:231 
  at Nova.Internal.Rendering.BatchGroupRenderer.Dispose () [0x0000d] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Rendering/BatchGroupRenderer.cs:404 
  at Nova.Internal.Utilities.Extensions.DictionaryExtensions.DisposeValues[K,V] (System.Collections.Generic.Dictionary`2[TKey,TValue] dict) [0x00019] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Utilities/Extensions/DictionaryExtensions.cs:43 
  at Nova.Internal.Rendering.RenderEngine.Dispose () [0x00097] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Rendering/RenderEngine.cs:619 
  at Nova.Internal.EngineManager.Dispose () [0x00031] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/EngineManager.cs:438 
  at Nova.Internal.Core.System`1[T].DomainReloadStarted () [0x00002] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Core/System.cs:50 
 #0 GetStacktrace(int)
 #1 DebugStringToFile(DebugStringToFileData const&)
 #2 DebugLogHandler_CUSTOM_Internal_Log(LogType, LogOption, ScriptingBackendNativeStringPtrOpaque*, ScriptingBackendNativeObjectPtrOpaque*)
 #3  (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)

System Nova.Editor.SceneViewInput Dispose failed with UnityEngine.UnityException: Internal_SetHotControl is not allowed to be called while application is terminating.
  at (wrapper managed-to-native) UnityEngine.GUIUtility.Internal_SetHotControl(int)
  at UnityEngine.GUIUtility.set_hotControl (System.Int32 value) [0x00001] in /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:116 
  at Nova.Editor.SceneViewInput.Dispose () [0x00030] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Editor/SceneViewInput.cs:432 
  at Nova.Internal.Core.System`1[T].DomainReloadStarted () [0x00002] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Core/System.cs:50 
 #0 GetStacktrace(int)
 #1 DebugStringToFile(DebugStringToFileData const&)
 #2 DebugLogHandler_CUSTOM_Internal_Log(LogType, LogOption, ScriptingBackendNativeStringPtrOpaque*, ScriptingBackendNativeObjectPtrOpaque*)
 #3  (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)

* Assertion at boehm-gc.c:1830, condition `type < HANDLE_TYPE_MAX' not met
```

</p>
</details>

**Comment by timcassell** [comment]
It looks like the crash is coming from something called Nova.

<details><summary>Log</summary>
<p>

``` cmd
Application is shutting down...
Cleanup mono
[40m[32minfo[39m[22m[49m: Unity.ILPP.Runner.PostProcessingAssemblyLoadContext[0]
      ALC ILPP context 1 is unloading
System Nova.Internal.DataStoreSystem Dispose failed with UnityEngine.UnityException: DestroyTransformAccessArray is not allowed to be called while application is terminating.
  at (wrapper managed-to-native) UnityEngine.Jobs.TransformAccessArray.DestroyTransformAccessArray(intptr)
  at UnityEngine.Jobs.TransformAccessArray.Dispose () [0x0001a] in /Users/bokken/build/output/unity/unity/Runtime/Transform/ScriptBindings/TransformAccessArray.bindings.cs:289 
  at Nova.Internal.Core.TransformDataStore`2[TDataStore,T].Dispose () [0x0002c] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Core/TransformDataStore.cs:221 
  at Nova.Internal.Layouts.LayoutDataStore.Dispose () [0x00001] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Layouts/LayoutDataStore.cs:758 
  at Nova.Internal.DataStoreSystem.Dispose () [0x00006] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/DataStoreSystem.cs:20 
  at Nova.Internal.Core.System`1[T].DomainReloadStarted () [0x00002] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Core/System.cs:50 
 #0 GetStacktrace(int)
 #1 DebugStringToFile(DebugStringToFileData const&)
 #2 DebugLogHandler_CUSTOM_Internal_Log(LogType, LogOption, ScriptingBackendNativeStringPtrOpaque*, ScriptingBackendNativeObjectPtrOpaque*)
 #3  (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)

System Nova.Internal.EngineManager Dispose failed with UnityEngine.UnityException: DestroyBuffer is not allowed to be called while application is terminating.
  at (wrapper managed-to-native) UnityEngine.ComputeBuffer.DestroyBuffer(UnityEngine.ComputeBuffer)
  at UnityEngine.ComputeBuffer.Dispose (System.Boolean disposing) [0x00007] in /Users/bokken/build/output/unity/unity/Runtime/Export/Shaders/ComputeBuffer.bindings.cs:44 
  at UnityEngine.ComputeBuffer.Dispose () [0x00001] in /Users/bokken/build/output/unity/unity/Runtime/Export/Shaders/ComputeBuffer.bindings.cs:35 
  at Nova.Internal.Rendering.ShaderBuffer.Dispose () [0x0000f] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Rendering/ShaderBuffer.cs:205 
  at Nova.Internal.Rendering.ShaderBufferUtils.SafeDispose (Nova.Internal.Rendering.ShaderBuffer shaderBuffer) [0x0000a] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Rendering/ShaderBuffer.cs:231 
  at Nova.Internal.Rendering.BatchGroupRenderer.Dispose () [0x0000d] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Rendering/BatchGroupRenderer.cs:404 
  at Nova.Internal.Utilities.Extensions.DictionaryExtensions.DisposeValues[K,V] (System.Collections.Generic.Dictionary`2[TKey,TValue] dict) [0x00019] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Utilities/Extensions/DictionaryExtensions.cs:43 
  at Nova.Internal.Rendering.RenderEngine.Dispose () [0x00097] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Rendering/RenderEngine.cs:619 
  at Nova.Internal.EngineManager.Dispose () [0x00031] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/EngineManager.cs:438 
  at Nova.Internal.Core.System`1[T].DomainReloadStarted () [0x00002] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Core/System.cs:50 
 #0 GetStacktrace(int)
 #1 DebugStringToFile(DebugStringToFileData const&)
 #2 DebugLogHandler_CUSTOM_Internal_Log(LogType, LogOption, ScriptingBackendNativeStringPtrOpaque*, ScriptingBackendNativeObjectPtrOpaque*)
 #3  (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)

System Nova.Editor.SceneViewInput Dispose failed with UnityEngine.UnityException: Internal_SetHotControl is not allowed to be called while application is terminating.
  at (wrapper managed-to-native) UnityEngine.GUIUtility.Internal_SetHotControl(int)
  at UnityEngine.GUIUtility.set_hotControl (System.Int32 value) [0x00001] in /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:116 
  at Nova.Editor.SceneViewInput.Dispose () [0x00030] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Editor/SceneViewInput.cs:432 
  at Nova.Internal.Core.System`1[T].DomainReloadStarted () [0x00002] in /Users/aomeara/git.arcspace/arcspace.unity-app/Assets/Plugins/Nova/Scripts/Internal/Core/System.cs:50 
 #0 GetStacktrace(int)
 #1 DebugStringToFile(DebugStringToFileData const&)
 #2 DebugLogHandler_CUSTOM_Internal_Log(LogType, LogOption, ScriptingBackendNativeStringPtrOpaque*, ScriptingBackendNativeObjectPtrOpaque*)
 #3  (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)

* Assertion at boehm-gc.c:1830, condition `type < HANDLE_TYPE_MAX' not met
```

</p>
</details>

**Comment by timcassell** [comment]
@drew-512 I think I fixed the crash.

**Comment by drew-512** [comment]
Been going ~6 hours now and zero crashes (has 3 or 4 by this time yesterday).  Will report end of tomorrow or so!

**Comment by timcassell** [comment]
So, this works by storing WeakReferences of each object so that they can be suppressed by the call to `ResetRuntimeContext`. WeakReferences add overhead, so I disabled the finalizers entirely in RELEASE mode. This means if a promise is not awaited properly, and it's rejected, that information will be lost. That's unfortunate, but I can't think of another way to support disabled domain reloads without adding overhead.

**Comment by timcassell** [comment]
> Still zero crashes since that patch from yesterday.

Yay!

> Yeah, concur that any additional overhead in release mode is the least preferred path.

Indeed. I started to implement adding detection to RejectContainers, but I realized I would have to mark them on every await, which adds overhead anyway. So I guess it'll just have to be that way in RELEASE mode. If a promise is not awaited or forgotten, it will only be detectable in DEBUG mode (including uncaught rejections).

> Maybe one idea is explicit promises could be flagged as "unobservable", which would basically mean that an exception isn't raised if they're not observed. I may be mistaken, but something like `await Promise.SwitchToForeground();` would only ever be unobserved in an Editor shutdown scenario.

The problem is _any_ promise could be unobserved in that scenario. `Promise.SwitchToForeground()` just happened to be what you got.

**Comment by timcassell** [comment]
Closing this as it appears the issue was actually fixed in #306.

**Pull request closed without merging**
